package emit

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/pulumi/component-to-crd/internal/schema"
)

// RenderScaffoldYAML emits a deterministic placeholder CRD scaffold.
func RenderScaffoldYAML(componentToken string, resource schema.Resource) []byte {
	propertyNames := sortedKeys(resource.InputProperties)
	requiredNames := append([]string(nil), resource.RequiredInputs...)
	sort.Strings(requiredNames)

	scaffold := fmt.Sprintf(`# Generated by component-to-crd.
# TODO: Pulumi inputProperties/requiredInputs to OpenAPI translation is not implemented yet.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: %s
spec:
  group: components.pulumi.local
  names:
    kind: Component
    plural: components
    singular: component
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: %s
          properties:
            spec:
              type: object
              properties: {}
`, yamlQuote(sanitizeDNSLabel(componentToken)), yamlQuote(
		fmt.Sprintf("placeholder scaffold for %s; observed inputProperties=%d (%s), requiredInputs=%d (%s)",
			componentToken,
			len(propertyNames),
			strings.Join(propertyNames, ", "),
			len(requiredNames),
			strings.Join(requiredNames, ", "),
		),
	))

	return []byte(scaffold)
}

func sortedKeys(values map[string]json.RawMessage) []string {
	if len(values) == 0 {
		return nil
	}

	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sanitizeDNSLabel(token string) string {
	if token == "" {
		return "component"
	}

	var b strings.Builder
	b.Grow(len(token))
	lastWasDash := false
	for _, r := range strings.ToLower(token) {
		isAlphaNum := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if isAlphaNum {
			b.WriteRune(r)
			lastWasDash = false
			continue
		}
		if !lastWasDash {
			b.WriteByte('-')
			lastWasDash = true
		}
	}

	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "component"
	}
	return out
}

func yamlQuote(value string) string {
	return strconv.Quote(value)
}
