package emit

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// RenderCRDYAML emits deterministic CRD YAML with the translated OpenAPI schema under spec.properties.spec.
func RenderCRDYAML(identity Identity, translatedSpecSchema map[string]any) ([]byte, error) {
	if translatedSpecSchema == nil {
		return nil, fmt.Errorf("translated spec schema is nil")
	}

	var b strings.Builder
	b.WriteString("# Generated by pulumi-component-to-crd.\n")
	b.WriteString("apiVersion: apiextensions.k8s.io/v1\n")
	b.WriteString("kind: CustomResourceDefinition\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: ")
	b.WriteString(yamlQuote(identity.MetadataName()))
	b.WriteByte('\n')
	b.WriteString("spec:\n")
	b.WriteString("  group: ")
	b.WriteString(identity.Group)
	b.WriteByte('\n')
	b.WriteString("  names:\n")
	b.WriteString("    kind: ")
	b.WriteString(identity.Kind)
	b.WriteByte('\n')
	b.WriteString("    plural: ")
	b.WriteString(identity.Plural)
	b.WriteByte('\n')
	b.WriteString("    singular: ")
	b.WriteString(identity.Singular)
	b.WriteByte('\n')
	b.WriteString("  scope: Namespaced\n")
	b.WriteString("  versions:\n")
	b.WriteString("    - name: ")
	b.WriteString(identity.Version)
	b.WriteByte('\n')
	b.WriteString("      served: true\n")
	b.WriteString("      storage: true\n")
	b.WriteString("      schema:\n")
	b.WriteString("        openAPIV3Schema:\n")
	b.WriteString("          type: object\n")
	b.WriteString("          properties:\n")
	b.WriteString("            spec:\n")
	if err := renderYAMLMap(&b, translatedSpecSchema, 14); err != nil {
		return nil, err
	}

	return []byte(b.String()), nil
}

func renderYAMLMap(b *strings.Builder, value map[string]any, indent int) error {
	keys := make([]string, 0, len(value))
	for key := range value {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		if err := renderYAMLKeyValue(b, key, value[key], indent); err != nil {
			return err
		}
	}
	return nil
}

func renderYAMLKeyValue(b *strings.Builder, key string, value any, indent int) error {
	b.WriteString(strings.Repeat(" ", indent))
	b.WriteString(key)
	b.WriteString(":")

	switch typed := value.(type) {
	case map[string]any:
		if len(typed) == 0 {
			b.WriteString(" {}\n")
			return nil
		}
		b.WriteByte('\n')
		return renderYAMLMap(b, typed, indent+2)
	case []any:
		return renderYAMLList(b, typed, indent)
	case []string:
		items := make([]any, 0, len(typed))
		for _, item := range typed {
			items = append(items, item)
		}
		return renderYAMLList(b, items, indent)
	default:
		encoded, err := renderYAMLScalar(typed)
		if err != nil {
			return err
		}
		b.WriteByte(' ')
		b.WriteString(encoded)
		b.WriteByte('\n')
		return nil
	}
}

func renderYAMLList(b *strings.Builder, values []any, indent int) error {
	if len(values) == 0 {
		b.WriteString(" []\n")
		return nil
	}

	b.WriteByte('\n')
	for _, item := range values {
		b.WriteString(strings.Repeat(" ", indent+2))
		b.WriteString("-")
		switch typed := item.(type) {
		case map[string]any:
			if len(typed) == 0 {
				b.WriteString(" {}\n")
				continue
			}
			b.WriteByte('\n')
			if err := renderYAMLMap(b, typed, indent+4); err != nil {
				return err
			}
		case []any:
			if len(typed) == 0 {
				b.WriteString(" []\n")
				continue
			}
			b.WriteByte('\n')
			if err := renderYAMLNestedList(b, typed, indent+4); err != nil {
				return err
			}
		default:
			encoded, err := renderYAMLScalar(typed)
			if err != nil {
				return err
			}
			b.WriteByte(' ')
			b.WriteString(encoded)
			b.WriteByte('\n')
		}
	}
	return nil
}

func renderYAMLNestedList(b *strings.Builder, values []any, indent int) error {
	for _, item := range values {
		b.WriteString(strings.Repeat(" ", indent))
		b.WriteString("-")
		switch typed := item.(type) {
		case map[string]any:
			if len(typed) == 0 {
				b.WriteString(" {}\n")
				continue
			}
			b.WriteByte('\n')
			if err := renderYAMLMap(b, typed, indent+2); err != nil {
				return err
			}
		case []any:
			if len(typed) == 0 {
				b.WriteString(" []\n")
				continue
			}
			b.WriteByte('\n')
			if err := renderYAMLNestedList(b, typed, indent+2); err != nil {
				return err
			}
		default:
			encoded, err := renderYAMLScalar(typed)
			if err != nil {
				return err
			}
			b.WriteByte(' ')
			b.WriteString(encoded)
			b.WriteByte('\n')
		}
	}
	return nil
}

func renderYAMLScalar(value any) (string, error) {
	switch typed := value.(type) {
	case string:
		return yamlQuote(typed), nil
	case bool:
		if typed {
			return "true", nil
		}
		return "false", nil
	case nil:
		return "null", nil
	case float64, float32, int, int64, int32, uint, uint64, uint32:
		encoded, err := json.Marshal(typed)
		if err != nil {
			return "", fmt.Errorf("render numeric scalar: %w", err)
		}
		return string(encoded), nil
	default:
		encoded, err := json.Marshal(typed)
		if err != nil {
			return "", fmt.Errorf("render scalar: %w", err)
		}
		if len(encoded) > 0 && encoded[0] == '{' {
			return "", fmt.Errorf("unsupported inline object scalar")
		}
		if len(encoded) > 0 && encoded[0] == '[' {
			return "", fmt.Errorf("unsupported inline array scalar")
		}
		return string(encoded), nil
	}
}

func yamlQuote(value string) string {
	return strconv.Quote(value)
}
